. Write a NumPy program to test whether none of the elements of a given array is zero.

In [8]:
import numpy as np
x=np.array([0,2,3,4])
print(f"original array: {x}")
print(f"Test if none of the elements of the said array is zero: {np.all(x)}")

original array: [0 2 3 4]
Test if none of the elements of the said array is zero: False


. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [12]:
import numpy as np
x=np.array([0,0,0,0])
print(f"original array: {x}")
print(f"Test whether any of the elements of a given array is non-zero: {np.any(x)}")

original array: [0 0 0 0]
Test whether any of the elements of a given array is non-zero: False


. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two
given

In [16]:
import numpy as np
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Comparison - equal:")
print(np.equal(x,y))
print(f"Comparison - equal within a tolerance:{np.allclose(x, y)}")

Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:True


4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.


In [20]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:",array)
array=np.ones(10)
print("An array of 10 ones:",array)
array=np.ones(10)*5
print("An array of 10 fives:",array)

An array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Write a NumPy program to create an array of the integers from 30 to70.


In [23]:
import numpy as np
array=np.arange(30,70)
print(array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


6. Write a NumPy program to create a 3x3 identity matrix


In [27]:
import numpy as np
array_2D = np.identity(3)
print(array_2D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Write a NumPy program to generate a random number between 0 and 1

In [33]:
import numpy as np
rand_num = np.random.normal(0, 1, 1)
print(rand_num)

[1.10250223]


. Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution

In [34]:
import numpy as np
rand_num = np.random.normal(0, 1, 15)
print(rand_num)

[ 1.10687445 -0.79245442  0.0218102   1.22639397 -0.5431627  -0.68546683
 -1.23952633  0.41667941 -0.88839126 -0.64267208  0.79062047 -0.30930241
  1.29600836  0.10216688  0.6099069 ]


. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values
except the first and last.


In [37]:
import numpy as np
array=np.arange(15,55)
print(array[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10


In [41]:
import numpy as np
x = np.random.randint(0, 11, 5)
print(x)

[1 4 1 0 1]


11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal
to 1, and inside 0

In [43]:
import numpy as np
x=np.ones((10,10))
x[1:-1 ,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2,
3, 4, 5.

In [44]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main
diagonal.


In [45]:
import numpy as np
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format)
and load it.


In [49]:
import numpy as np
import os
x = np.arange(10)
y = np.arange(11, 20)
print("Original arrays:")
print(x)
print(y)
np.savez('temp_arra.npz', x=x, y=y)
print("Load arrays from the 'temp_arra.npz' file:")
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)


Original arrays:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
Load arrays from the 'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.
Select

In [51]:
import numpy as np
np.random.seed(10)
print(np.random.rand(40))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]


16. Write a NumPy program to extract all numbers from a given array which are less and greater than a
specified number.

In [52]:
import numpy as np
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 4.38, 6.99],
              [1.54, 2.39, 9.29]])
print("Original array:")
print(nums)
n=5
print("\nElements of the said array greater than", n)
print(nums[nums > n])
n = 6
print("\nElements of the said array less than", n)
print(nums[nums < n])

Original array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Elements of the said array greater than 5
[5.54 7.99 6.99 9.29]

Elements of the said array less than 6
[5.54 3.38 3.54 4.38 1.54 2.39]
